# Generated by Django 6.0.5 on 2026-05-30 17:57

from django.db import migrations, models


def merge_duplicate_cart_items(apps, schema_editor):
    CartItem = apps.get_model('orders', 'CartItem')
    duplicates = (
        CartItem.objects
        .values('cart_id', 'variant_id')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        items = list(
            CartItem.objects
            .filter(cart_id=duplicate['cart_id'], variant_id=duplicate['variant_id'])
            .order_by('id')
        )
        keeper = items[0]
        keeper.quantity = sum(item.quantity for item in items)
        keeper.save(update_fields=['quantity'])
        CartItem.objects.filter(id__in=[item.id for item in items[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon'),
        ('products', '0003_product_delivery_type_product_platform_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_cart_items, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
