# Generated by Django 6.0.5 on 2026-08-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderstatusaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusaudit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_audits', to='orders.order'),
        ),
    ]
