# Generated by Django 6.0.5 on 2026-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, default='کد دیجیتال فوری', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, default='گلوبال', max_length=100),
        ),
    ]
